//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labaEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int Id { get; set; }
        public string AmountBonus { get; set; }
    
        public virtual User User { get; set; }
    }
}
