//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labaEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int Id { get; set; }
        public int Price { get; set; }
        public string Name { get; set; }
        public byte[] PhotoPath { get; set; }
        public int ProviderId { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
